# Generated by Django 2.1.7 on 2019-04-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0007_auto_20190330_1655'),
        ('users', '0008_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationScholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organisation')),
                ('scholarship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Scholarship')),
            ],
        ),
    ]
