# Generated by Django 2.1.7 on 2019-04-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationscholarship',
            old_name='organisation_id',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='organisationscholarship',
            old_name='scholarship_id',
            new_name='scholarship',
        ),
    ]
