# Generated by Django 2.1.7 on 2019-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
