# Generated by Django 2.1.7 on 2019-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20190310_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
