# Generated by Django 2.1.7 on 2019-03-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_scholarshipeligibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipeligibility',
            old_name='scholarship_id',
            new_name='scholarship',
        ),
    ]
