# Generated by Django 2.1.7 on 2019-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20190317_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
